### ISSUE TITLE
Remove APICredential-based machinery

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/commonground-api-common#7]
We can rely 100% on zgw-consumers instead of having this mixed approach based on a vanilla gemma-zds-client implementation.

zgw-consumers is richer and provides django support. The core mechanisms (`get_auth` etc.) should be adapted to build on top of zgw-consumers.

**Comment by annashamray** [comment]
Open Notificaties which heavily relies on APICredential should not be forgotten here
